### ISSUE TITLE
Type system / Glossary / Type parameter

### ISSUE THREAD

**Issue by d-nulR** [Kotlin/kotlin-spec#33]
Actual:  "Formal type argument of a type constructor"
Proposal: "Formal type parameter of a type constructor" or better "Formal parameter of a type constructor"

**Comment by ice-phoenix** [comment]
In these two definitions (`Type parameter` and `Type argument`) we want to establish their meaning and difference without relying on any common meaning of "parameter" vs "argument" (as it differs between different areas and programming languages). Therefore, we need either "formal argument"/"actual argument" or "formal parameter"/"actual parameter", so that there is an axis on which they are different. We decided to use the former; maybe we should switch to the latter.

Do you have any thoughts on why using "parameter" is better?

**Comment by d-nulR** [comment]
Relying on common interpretation of terms like  "parameter" and "argument" can make a definition more clear. I think that "formal type argument" and  "actual type parameter" are a bad idea, but it is up to you.
